@startuml

participant Magazines
actor       Journalist
participant Articles as "Articles"
participant ArticleReviews as "Article Reviews"
actor       Copywriter

autonumber

Journalist -> Magazines: Views magazine topics

Journalist -> Articles: Submits a draft article for a topic
Articles -->> ArticleReviews: Draft article created

ArticleReviews -> ArticleReviews: Begin article review
ArticleReviews <-]: Assign a copywriter for a review

Copywriter -> Articles: Views the draft article
Copywriter -> ArticleReviews: Suggests changes to the draft article
Journalist -> ArticleReviews: Views suggested changes
Journalist -> Articles: Edits the draft article

Articles -->> ArticleReviews: Draft article edited

Journalist -> ArticleReviews: Marks the suggested change as applied
Copywriter -> Articles: Views the draft article
Copywriter -> ArticleReviews: Marks the suggested change as resolved

Journalist -> Articles: Publishes the article
activate Articles
Articles -> ArticleReviews: Checks Article Review Status
Articles <- ArticleReviews: Approved (No Unresolved Change Suggestions)
Journalist <- Articles: Successful response
deactivate Articles

Articles -->> ArticleReviews: Article Published

@enduml